version: '3'
services:
  db:
    image: mongo
    ports:
     - 27017:27017
  
  api:
    build: .
    ports:
     - "3001:3001"
    environment:
     - "NODE_ENV=docker"
     - "PORT=3001"
    depends_on:
     - db
    